# This is a basic workflow that is manually triggered

name: deployGitHubPages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run build
        env:
          VUE_APP_API_KEY_FIREBASE: ${{ secrets.VUE_APP_API_KEY_FIREBASE }}
      - name: git init
        run: git init
      - name: git add
        run: git add .
      - name: git commit
        run: git commit -m "deploy"
      - name: git add remote
        run: git remote add origin https://github.com/imcrisam/ImCrisam.github.io.git
      - name: git push
        run: git push origin main --force



        
